using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
// Solution template generated by caide

class Solution {
    public void solve(TextReader input, TextWriter output) {
    }
}

