- ignore: {name: 'Use :'}
- ignore: {name: Redundant bracket}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use uncurry}
- ignore: {name: Eta reduce}
- ignore: {name: 'Avoid lambda using `infix`'}
- ignore: {name: Use map once}
