using System;
using System.Linq;
using System.IO;
// Solution template generated by caide

class Solution {
    public void solve(TextReader input, TextWriter output) {
    }
}

public class Program {
    public static void Main(string[] args) {
        Solution solution = new Solution();
        solution.solve(System.Console.In, System.Console.Out);
    }
}

